<a href="https://colab.research.google.com/github/Jaykumaran/ANN-Customer-Churn-Prediction/blob/main/BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install -U "tensorflow==2.8.*"
!pip install -U "tensorflow-text==2.8.*"





     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 MB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 47.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 57.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.3/462.3 kB 31.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 51.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 64.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 39.5 MB/s eta 0:00:00
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.13.0
    Uninstalling tensorflow-estimator-2.13.0:
      Successfully uninstalled tensorflow-estimator-2.13.0
  Attempting uninstall: keras
    Found existing installation: keras 2.13.1
    Uninstalling keras-2.13.1:
      Successfully uninstalled keras-2.13.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 14.1 MB/s eta 0:00:00
  Attempting uninstall: tensorflow-text
    Found existing installation: tensorflow-text 2.13.0
    Uninstalling tensorflow-text-2.13.0:
      Successfully uninstalled tensorflow-text-2.13.0


ImportError: ignored

import tensorflow_hub as hub
import tensorflow_text as text

In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [6]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'


In [3]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [4]:
text_test = ['nice movie indeed','i like python']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed

{'input_type_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_mask': <tf.Tensor: shape

In [ ]:
# CLS nice movie indeed SEP  reason why 5 ones in input mask for first

In [7]:
#Creating another model
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs'])

In [8]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177415, -0.21411918,  0.49769545, ...,  0.24465223,
        -0.47334486,  0.81758714],
       [-0.8689867 , -0.30780745,  0.00704767, ...,  0.03655439,
        -0.6218916 ,  0.88935775]], dtype=float32)>

In [10]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567826,  0.14476815, ..., -0.09677101,
          0.08722129,  0.07711115],
        [ 0.17839423, -0.19006102,  0.50349426, ..., -0.0586982 ,
          0.32717055, -0.1557847 ],
        [ 0.18701506, -0.43388772, -0.48875096, ..., -0.15502794,
          0.00145145, -0.24470927],
        ...,
        [ 0.12083083,  0.12884235,  0.46453506, ...,  0.07375502,
          0.17441955,  0.16522071],
        [ 0.07967877, -0.01190688,  0.5022537 , ...,  0.13777734,
          0.2100222 ,  0.00624607],
        [-0.07212669, -0.2830346 ,  0.59033346, ...,  0.4755189 ,
          0.16668485, -0.08920346]],

       [[ 0.06995865,  0.16243811, -0.20879403, ..., -0.07444035,
          0.23979053,  0.43425843],
        [ 0.20101269,  0.04631477, -0.24773955, ...,  0.11454864,
          0.6436775 ,  0.28652674],
        [ 0.5094474 ,  0.34912974,  0.93149066, ...,  0.40963614,
          0.5508081 ,  0.08211748],
        ...,

In [12]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901431,  0.00644744, -0.03614963, ...,  0.04999617,
           0.06149197, -0.02657544],
         [ 1.1753383 ,  1.2140785 ,  1.1569982 , ...,  0.11634368,
          -0.35855377, -0.4049018 ],
         [ 0.03859037,  0.5386998 , -0.21089777, ...,  0.21858189,
           0.7260167 , -1.1158606 ],
         ...,
         [-0.07587016, -0.25421906,  0.70755124, ...,  0.5054201 ,
          -0.18878679,  0.1502834 ],
         [-0.16066605, -0.28089684,  0.5759707 , ...,  0.5275854 ,
          -0.11141382,  0.02887549],
         [-0.04428151, -0.2027958 ,  0.59093547, ...,  0.8133835 ,
          -0.39075807, -0.02601741]],
 
        [[ 0.1506246 , -0.04627926, -0.1185271 , ..., -0.02714248,
           0.12737712,  0.00902428],
         [ 0.6680788 ,  1.11233   , -0.44477648, ...,  0.46429083,
           1.0316627 ,  0.01049969],
         [ 0.16644813,  1.0569066 ,  0.4476963 , ..., -0.14060241,
           0.83627945, -0.09